load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_proto",
    sha256 = "66bfdf8782796239d3875d37e7de19b1d94301e8972b3cbd2446b332429b4df1",
    strip_prefix = "rules_proto-4.0.0",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/refs/tags/4.0.0.tar.gz",
    ],
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

local_repository(
    name = "rules_buf",
    path = "../",
)

load("@rules_buf//:repo.bzl", "rules_buf_toolchains")

rules_buf_toolchains()


load("@rules_buf//:image.bzl", "buf_image")

buf_image(
    name = "petapis",
    module = "buf.build/alex/petapis",
    commit = "ed11b653d2f74267a3fa009f7c37f69a",
    sha256 = "e824b046b36047fd4d13f23919cbe3fe09653a28de5a5b5940a1a219aac3c44d",
)