package(default_visibility = ["//:__subpackages__"])

proto_library(
    name = "google_type_proto",
    srcs = ["datetime.proto"],
    deps = [
        "@com_google_protobuf//:duration_proto",
    ],
)
