name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
# Bazelisk is included in github runners
# Bazel cache: https://docs.bazel.build/versions/main/output_directories.html
  linux:
    runs-on: ubuntu-latest
    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2     
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache
      - uses: actions/checkout@v2
      - name: bazel test
        run: bazel --output_base=~/.cache/bazel test //...
  macos:
    runs-on: macos-latest
    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2     
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-cache
      - uses: actions/checkout@v2
      - name: bazel test
        run: bazel --output_base=~/.cache/bazel test //...
  windows:
    runs-on: windows-latest
    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2     
        with:
          path: |
            ${{ env.LOCALAPPDATA }}\bazelisk
            ${{ env.LOCALAPPDATA }}\bazel
          key: ${{ runner.os }}-bazel-cache
      - uses: actions/checkout@v2
      - name: bazel test
        run: bazel test --output_base=${{ env.LOCALAPPDATA }}\bazel //...
