name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
# Bazelisk is included in github runners
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bazel test
        run: bazel test //...
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: bazel test
        run: bazel test //...
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: bazel test
        run: bazel test //...
